const {test,expect}=require('@playwright/test');
const {expectNoHorizontalOverflow,collectBrowserErrors,expectNoBrowserErrors}=require('./support');
async function central(page){await page.goto('/index.html?qa=1');await page.locator('#eventOperations summary').click();}
test('canais mostram pendências sem afirmar entrega',async({page})=>{const errors=collectBrowserErrors(page);await central(page);await page.locator('[data-ops-tab="channels"]').click();await expect(page.locator('#eventOperations')).toContainText('Ativação pendente');await expect(page.locator('#eventOperations')).toContainText('Respostas de e-mail');await page.locator('[data-ops-channel="zapi"]').click();await expect(page.locator('dialog')).toHaveCount(0);await expectNoBrowserErrors(errors);});
test('mensagem ambígua só entra na conversa após vínculo revisado',async({page})=>{
 await central(page);await page.evaluate(()=>{eventOps.providerEvents=[{id:'provider-fixture',kind:'inbound',state:'triage',channel:'whatsapp',destination:'5521999999999',body:'Quero alterar o horário',occurred_at:new Date().toISOString()}];renderEventOperations();});
 await page.locator('[data-ops-tab="inbox"]').click();await expect(page.getByRole('region',{name:'Mensagens para vincular'})).toContainText('Quero alterar');
 await page.locator('[data-ops-link]').click();const d=page.locator('.event-ops-dialog');await d.locator('[name="event"]').selectOption('qa-opp-qa-proposal-sem-resposta');await d.getByRole('button',{name:'Vincular',exact:true}).click();await expect(d).toHaveCount(1);await d.locator('input[type="checkbox"]').check();await d.getByRole('button',{name:'Vincular',exact:true}).click();await expect(d).toHaveCount(0);
 await page.locator('[data-ops-selector]').selectOption('qa-opp-qa-proposal-sem-resposta');await expect(page.locator('.event-ops-thread')).toContainText('Quero alterar o horário');await expect(page.locator('.event-ops-thread')).toContainText('Canal integrado');
});
test('abertura de e-mail continua sem confirmação de leitura humana',async({page})=>{await central(page);await page.evaluate(()=>{eventOps.outbox=[{destination:'cliente@example.test',channel:'email',status:'accepted',engagement:'opened',created_at:new Date().toISOString()}];renderEventOperations();});await page.locator('[data-ops-tab="sends"]').click();await expect(page.locator('#eventOperations')).toContainText('entrega não confirmada');await expect(page.locator('#eventOperations')).toContainText('pode ser automática');});
for(const width of [320,1440])test(`triagem e canais cabem em ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await central(page);await page.locator('[data-ops-tab="channels"]').click();await expectNoHorizontalOverflow(page);});
