-- SQL fixtures only; all writes and simulated test identity roll back. No provider calls.
begin;
do $$
declare actor uuid; o1 uuid; o2 uuid; p uuid; b uuid; eb uuid; ev uuid; msg uuid; result jsonb; at timestamptz:=now()-interval '1 minute'; payload jsonb; blocked boolean; test_phone text:='55219'||lpad((floor(random()*1e8)::bigint)::text,8,'0'); test_email text:=gen_random_uuid()::text||'@example.test';
begin
  assert not has_function_privilege('anon','public.ingest_event_provider_events(text,jsonb)','EXECUTE'),'Anonymous ingress forbidden';
  assert not has_function_privilege('authenticated','public.event_channel_worker_config(text)','EXECUTE'),'Worker secrets forbidden to sellers';
  assert not has_table_privilege('authenticated','event_private.channel_credentials','SELECT'),'Private keys forbidden';
  assert not has_function_privilege('authenticated','public.event_delivery_sync_result(boolean,text)','EXECUTE'),'Only worker enables successful OAuth polling';
  assert not has_table_privilege('anon','public.event_provider_events','SELECT'),'Anonymous message access forbidden';
  select id into actor from auth.users where email='leorangel@gmail.com' limit 1;
  assert actor is not null,'Test actor exists';
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','leorangel@gmail.com','role','authenticated')::text,true);
  insert into public.oportunidades(cliente_nome,cliente_email,cliente_whatsapp,data_evento,status) values('Channel fixture A',test_email,substr(test_phone,3),'2099-12-01','proposta_pronta') returning id into o1;
  insert into public.propostas(oportunidade_id,cliente_nome,cliente_email,cliente_whatsapp,data_evento,horario_evento,convidados,duracao,subtotal,taxa_servico,privatizacao,total,status,publication_status,snapshot)
    values(o1,'Channel fixture',test_email,substr(test_phone,3),'2099-12-01','10:00',20,2,1000,120,0,1120,'proposta_pronta','ready','{"event":{},"totals":{"adjustment":0}}') returning id into p;
  result:=public.begin_event_send(p,'whatsapp',test_phone,'Channel fixture','Fixture',null);
  b:=(result#>>'{send,id}')::uuid;
  payload:=jsonb_build_array(jsonb_build_object('key','fixture-early-read','channel','whatsapp','kind','status','message_id','fixture-provider-wa','destination',test_phone,'signal','read','occurred_at',at));
  result:=public.ingest_event_provider_events('zapi',payload);
  ev:=(result->>0)::uuid;
  assert (select state='pending' from public.event_provider_events where id=ev),'Early receipt persists';
  perform public.finish_event_send(b,'accepted','fixture-provider-wa');
  perform public.reconcile_event_receipts(b);
  assert (select delivery_status='read' and status='accepted' from public.event_outbox where id=b),'Read receipt reconciles without changing send dedup status';
  assert (select delivery_status='read' from public.event_messages where external_id='send:'||b),'Thread shows receipt';
  perform public.ingest_event_provider_events('zapi',payload);
  assert (select count(*)=1 from public.event_provider_events where id=ev),'Duplicate receipt stays single';
  perform public.ingest_event_provider_events('zapi',jsonb_build_array(jsonb_build_object('key','fixture-late-sent','channel','whatsapp','kind','status','message_id','fixture-provider-wa','destination',test_phone,'signal','accepted','occurred_at',clock_timestamp())));
  assert (select delivery_status='read' from public.event_outbox where id=b),'SENT cannot regress read';
  result:=public.ingest_event_provider_events('zapi',jsonb_build_array(jsonb_build_object('key','fixture-inbound-1','channel','whatsapp','kind','inbound','message_id','fixture-inbound-1','destination',test_phone,'body','Trocar horário','occurred_at',clock_timestamp())));
  assert (select state='applied' and opportunity_id=o1 from public.event_provider_events where id=(result->>0)::uuid),'Single active exact contact auto-links including Brazilian prefix';
  assert (select proxima_acao='Responder mensagem do cliente' from public.oportunidades where id=o1),'Inbound prioritizes response';
  assert (select ultimo_contato_em<ultima_resposta_cliente_em from public.oportunidades where id=o1),'Inbound never invents outbound contact';
  insert into public.oportunidades(cliente_nome,cliente_whatsapp,data_evento,status) values('Channel fixture B',test_phone,'2099-12-02','lead_recebido') returning id into o2;
  payload:=jsonb_build_array(jsonb_build_object('key','fixture-ambiguous','channel','whatsapp','kind','inbound','message_id','fixture-ambiguous','destination',test_phone,'body','Qual o preço?','occurred_at',clock_timestamp()));
  result:=public.ingest_event_provider_events('zapi',payload); ev:=(result->>0)::uuid;
  assert (select state='triage' and message_id is null from public.event_provider_events where id=ev),'Ambiguous contact remains triage';
  perform public.resolve_event_inbound(ev,o2,false);
  assert (select state='applied' and opportunity_id=o2 and resolved_by=actor from public.event_provider_events where id=ev),'Human link audited';
  perform public.ingest_event_provider_events('zapi',payload);
  assert (select count(*)=1 from public.event_messages where external_id='zapi:fixture-ambiguous'),'Inbound retry does not duplicate thread';
  result:=public.ingest_event_provider_events('mailbox',jsonb_build_array(jsonb_build_object('key','fixture-unknown','channel','email','kind','inbound','message_id','fixture-unknown','destination','unknown-channel@example.test','body','Olá','occurred_at',clock_timestamp())));
  ev:=(result->>0)::uuid;
  perform public.resolve_event_inbound(ev,null,true);
  assert (select state='ignored' and opportunity_id is null from public.event_provider_events where id=ev),'Ignoring creates no event';
  result:=public.begin_event_send(p,'email',test_email,'Email fixture','Fixture',(select ultima_resposta_cliente_em from public.oportunidades where id=o1));
  eb:=(result#>>'{send,id}')::uuid;perform public.finish_event_send(eb,'accepted','fixture-email-provider');
  update public.propostas set cliente_resposta_em=at where id=p;
  assert (select ultima_resposta_cliente_em>at from public.oportunidades where id=o1),'Saving proposal cannot regress newer channel response';
  payload:=jsonb_build_array(jsonb_build_object('key','fixture-email-open','channel','email','kind','status','message_id','fixture-email-provider','provider_reference','fixture-email@example.test','send_id',eb,'send_attempt',1,'destination',test_email,'signal','opened','occurred_at',clock_timestamp()));
  perform public.ingest_event_provider_events('zepto',payload);
  assert (select engagement='opened' and delivery_status is null from public.event_outbox where id=eb),'Open is not delivery proof';
  perform public.ingest_event_provider_events('zepto',jsonb_build_array(jsonb_build_object('key','fixture-email-delivery','channel','email','kind','status','message_id','fixture-email-provider','destination',test_email,'signal','delivered','occurred_at',clock_timestamp())));
  assert (select delivery_status='delivered' from public.event_outbox where id=eb),'Exact receipt confirms email delivery';
  result:=public.ingest_event_provider_events('mailbox',jsonb_build_array(jsonb_build_object('key','fixture-email-reply','channel','email','kind','inbound','message_id','fixture-email-reply','reply_to_id','fixture-email@example.test','destination',test_email,'body','Pode enviar opções?','occurred_at',clock_timestamp())));
  assert (select opportunity_id=o1 and state='applied' from public.event_provider_events where id=(result->>0)::uuid),'RFC Message-ID alias links mail response';
  update public.event_outbox set status='failed' where id=eb;
  result:=public.begin_event_send(p,'email',test_email,'Email fixture','Fixture',(select ultima_resposta_cliente_em from public.oportunidades where id=o1));
  assert not (result->>'claimed')::boolean,'Proven delivery never reclaims a failed send';
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','eventos@embaixadacarioca.com.br','role','authenticated')::text,true);
  blocked:=false;begin perform public.get_event_channel_setup();exception when others then blocked:=true;end;
  assert blocked,'Seller cannot obtain setup keys';
  blocked:=false;begin perform public.configure_event_channel('zapi','instance',true);exception when others then blocked:=true;end;
  assert blocked,'Seller cannot activate channels';
end; $$;
rollback;
