-- Executar como administrador do banco. Fixtures isoladas; nenhuma chamada externa.
begin;
do $$
declare actor uuid; o1 uuid; o2 uuid; p1 uuid; p2 uuid; message_id uuid:=gen_random_uuid(); claim jsonb; retry jsonb; response_at timestamptz; blocked boolean; row_count integer; token uuid; public_data jsonb;
begin
  select id into actor from auth.users where lower(email)='leorangel@gmail.com' limit 1;
  assert actor is not null, 'Gestor de teste indisponível';
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','leorangel@gmail.com','role','authenticated')::text,true);
  perform public.save_event_commercial_policy(60,null);
  insert into public.oportunidades(cliente_nome,data_evento,status) values('Fixture P0/P1 A','2099-10-10','proposta_pronta') returning id into o1;
  insert into public.oportunidades(cliente_nome,data_evento,status) values('Fixture P0/P1 B','2099-10-10','proposta_pronta') returning id into o2;
  insert into public.propostas(oportunidade_id,cliente_nome,data_evento,horario_evento,convidados,duracao,subtotal,taxa_servico,privatizacao,total,status,publication_status,snapshot)
    values(o1,'Fixture A','2099-10-10','22:00',40,3,10000,1200,0,11200,'proposta_pronta','ready','{"event":{},"totals":{"adjustment":0},"publicOfferOptions":[{"base":true,"total":11200},{"name":"Complemento","total":12000}],"offerConfiguration":{"internal":true}}') returning id,public_token into p1,token;
  insert into public.propostas(oportunidade_id,cliente_nome,data_evento,horario_evento,convidados,duracao,subtotal,taxa_servico,privatizacao,total,status,publication_status,snapshot)
    values(o2,'Fixture B','2099-10-11','00:00',40,2,10000,1200,0,11200,'proposta_pronta','ready','{"event":{},"totals":{"adjustment":0}}') returning id into p2;
  perform public.plan_event_opportunities(array[o1],'eventos@embaixadacarioca.com.br','Responder cliente',now()+interval '1 hour');
  assert (select metadata->>'first_reply_sent_at' is null from public.oportunidades where id=o1), 'Plano não é contato';
  perform public.record_event_message(o1,'Preciso de ajuste','email','inbound',now()-interval '1 minute',message_id);
  perform public.record_event_message(o1,'Preciso de ajuste','email','inbound',now()-interval '1 minute',message_id);
  select count(*) into row_count from public.event_messages where id=message_id;
  assert row_count=1,'Registro repetido deve ser único';
  blocked:=false;
  begin perform public.record_event_message(o2,'Outra mensagem','email','inbound',now(),message_id); exception when others then blocked:=true; end;
  assert blocked,'Idempotência não pode misturar eventos';
  assert (select proxima_acao='Responder mensagem do cliente' from public.oportunidades where id=o1),'Resposta deve suspender cobrança';
  perform public.mark_event_messages_read(o1,array[message_id]);
  assert (select read_at is not null from public.event_messages where id=message_id),'Leitura deve ser registrada';
  select ultima_resposta_cliente_em into response_at from public.oportunidades where id=o1;
  blocked:=false;
  begin perform public.begin_event_send(p1,'email','fixture@example.test','Resposta revisada','Fixture',null); exception when others then blocked:=true; end;
  assert blocked,'Resposta nova invalida contexto anterior';
  claim:=public.begin_event_send(p1,'email','fixture@example.test','Resposta revisada','Fixture',response_at);
  retry:=public.begin_event_send(p1,'email','fixture@example.test','Resposta revisada','Fixture',response_at);
  assert (claim->>'claimed')::boolean and not (retry->>'claimed')::boolean,'Envio concorrente não pode ser repetido';
  perform public.finish_event_send((claim#>>'{send,id}')::uuid,'accepted','fixture-provider',null);
  assert (select metadata->>'first_reply_sent_at' is not null from public.oportunidades where id=o1),'Aceitação deve registrar contato';
  assert (select snapshot#>>'{event,signalDeadlineAt}' is not null from public.propostas where id=p1),'Prazo do sinal deve existir';
  retry:=public.begin_event_send(p1,'email','fixture@example.test','Resposta revisada','Fixture',response_at);
  assert not (retry->>'claimed')::boolean and retry#>>'{send,status}'='accepted','Aceitação não pode reenviar';
  claim:=public.begin_event_send(p1,'email','fixture@example.test','Outro texto revisado','Fixture',response_at);
  perform public.finish_event_send((claim#>>'{send,id}')::uuid,'uncertain',null,'Timeout simulado');
  retry:=public.begin_event_send(p1,'email','fixture@example.test','Outro texto revisado','Fixture',response_at);
  assert not (retry->>'claimed')::boolean,'Incerteza não autoriza nova tentativa';
  claim:=public.begin_event_send(p1,'email','fixture@example.test','Texto recusado','Fixture',response_at);
  perform public.finish_event_send((claim#>>'{send,id}')::uuid,'failed',null,'400 simulado');
  retry:=public.begin_event_send(p1,'email','fixture@example.test','Texto recusado','Fixture',response_at);
  assert (retry->>'claimed')::boolean and (retry#>>'{send,attempts}')::integer=2,'Recusa conhecida admite nova aprovação';
  update public.propostas set snapshot=jsonb_set(snapshot,'{totals,adjustment}','-2000'),total=9200 where id=p1;
  blocked:=false;
  begin perform public.begin_event_send(p1,'email','fixture@example.test','Com desconto','Fixture',response_at); exception when others then blocked:=true; end;
  assert blocked,'Desconto exige alçada';
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','eventos@embaixadacarioca.com.br','role','authenticated')::text,true);
  blocked:=false; begin perform public.approve_event_discount(p1); exception when others then blocked:=true; end;
  assert blocked,'Vendedor não aprova como gestor';
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','leorangel@gmail.com','role','authenticated')::text,true);
  perform public.approve_event_discount(p1);
  claim:=public.begin_event_send(p1,'email','fixture@example.test','Com desconto','Fixture',response_at);
  assert (claim->>'claimed')::boolean,'Gestor autentica versão';
  update public.propostas set snapshot=jsonb_set(snapshot,'{totals,adjustment}','-2100'),total=9100 where id=p1;
  assert (select not valid from public.get_event_discount_approvals() where proposal_id=p1),'Preço alterado invalida alçada';
  update public.propostas set snapshot=jsonb_set(snapshot,'{totals,adjustment}','0'),total=11200 where id=p1;
  perform public.hold_event_proposal(p1,now()+interval '1 hour');
  blocked:=false; begin perform public.hold_event_proposal(p2,now()+interval '1 hour'); exception when others then blocked:=true; end;
  assert blocked,'Agenda sobreposta atravessando meia-noite deve limitar capacidade';
  update public.propostas set convidados=20 where id=p2;
  perform public.hold_event_proposal(p2,now()+interval '1 hour');
  update public.event_reservations set expires_at=now()-interval '1 minute' where opportunity_id=o1;
  update public.propostas set convidados=40 where id=p2;
  perform public.hold_event_proposal(p2,now()+interval '1 hour');
  blocked:=false; begin update public.propostas set status='confirmado' where id=p2; exception when others then blocked:=true; end;
  assert blocked,'Confirmação exige sinal registrado';
  update public.propostas set snapshot=snapshot||'{"pagamentoSinal":{"valor":5600}}',status='confirmado' where id=p2;
  assert (select status='confirmed' from public.event_reservations where opportunity_id=o2),'Confirmação deve reservar';
  update public.propostas set status='cancelado' where id=p2;
  assert (select status='released' from public.event_reservations where opportunity_id=o2),'Cancelamento deve liberar';
  select to_jsonb(x) into public_data from public.get_public_proposal(token) x;
  assert public_data#>'{snapshot,publicOfferOptions}' is not null,'Comparação pública disponível';
  assert public_data#>'{snapshot,offerConfiguration}' is null,'Configuração interna não é pública';
  assert not has_table_privilege('anon','public.event_messages','SELECT'),'Anônimo não lê conversas';
  assert not has_table_privilege('authenticated','public.event_outbox','UPDATE'),'Cliente não edita ledger';
  assert not has_function_privilege('authenticated','public.finish_event_send(uuid,text,text,text)','EXECUTE'),'Somente worker finaliza envio';
  assert not has_function_privilege('anon','public.begin_event_send(uuid,text,text,text,text,timestamptz)','EXECUTE'),'Envio não é público';
  assert not has_function_privilege('authenticated','public.begin_event_send(uuid,text,text,text,text)','EXECUTE'),'Assinatura antiga não contorna revisão';
  perform set_config('request.jwt.claims','{}',true);
  blocked:=false;begin perform public.get_event_discount_approvals();exception when others then blocked:=true;end;
  assert blocked,'RPC de alçada exige equipe';
end $$;
rollback;
