-- Isolated fixtures, real PostgreSQL permissions; every write is rolled back.
begin;
do $$
declare actor uuid; opp uuid; p public.propostas; saved public.propostas;
  request_id uuid:=gen_random_uuid(); response record; duplicate record; blocked boolean;
begin
  select id into actor from auth.users where email='leorangel@gmail.com' limit 1;
  assert not has_table_privilege('anon','public.solicitacoes_cotacao','INSERT'), 'Anonymous capture must use RPC';
  assert not has_table_privilege('authenticated','public.propostas','UPDATE'), 'Team updates must use revision RPC';
  assert not has_table_privilege('authenticated','public.propostas','INSERT'), 'Team inserts must use version RPC';
  assert not has_function_privilege('anon','public.respond_public_proposal(uuid,text,date,time,integer,text,jsonb)','EXECUTE'), 'Legacy response cannot bypass revision';
  assert not has_table_privilege('anon','event_private.public_response_requests','SELECT'), 'Response journal is private';
  insert into public.oportunidades(cliente_nome,status) values('Priority fixture','proposta_enviada') returning id into opp;
  insert into public.propostas(oportunidade_id,cliente_nome,cliente_email,status,publication_status,snapshot)
    values(opp,'Priority fixture','priority@example.test','proposta_enviada','sent','{}') returning * into p;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','leorangel@gmail.com','role','authenticated')::text,true);
  set local role authenticated;
  select * into saved from public.save_event_proposal(p.id,'{"snapshot":{"marker":"first"}}',p.revision,null);
  assert saved.revision=p.revision+1, 'Successful write increments revision';
  blocked:=false;
  begin perform public.save_event_proposal(p.id,'{"snapshot":{"marker":"stale"}}',p.revision,null);
  exception when sqlstate 'PT409' then blocked:=true; end;
  assert blocked,'Stale write must be refused';
  assert (select snapshot->>'marker'='first' from public.propostas where id=p.id),'Stale write must not overwrite';
  blocked:=false;
  begin update public.propostas set snapshot='{}' where id=p.id;
  exception when insufficient_privilege then blocked:=true; end;
  assert blocked,'Direct authenticated write must be refused';
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','outsider@example.test','role','authenticated')::text,true);
  blocked:=false;
  begin perform public.save_event_proposal(p.id,'{}',saved.revision,null);
  exception when others then blocked:=true; end;
  assert blocked,'Non-team account must be refused';
  reset role;
  select * into p from public.propostas where id=p.id;
  set local role anon;
  blocked:=false;
  begin insert into public.solicitacoes_cotacao(cliente_nome,cliente_email,snapshot) values('Bypass','bypass@example.test','{}');
  exception when insufficient_privilege then blocked:=true; end;
  assert blocked,'Anonymous direct insert must fail';
  blocked:=false;
  begin perform public.respond_public_proposal_v2(p.public_token,'alteracao',gen_random_uuid(),p.id,p.revision-1,null,null,null,'Ajuste de data',null);
  exception when sqlstate 'PT409' then blocked:=true; end;
  assert blocked,'Public response must refer to reviewed revision';
  select * into response from public.respond_public_proposal_v2(p.public_token,'alteracao',request_id,p.id,p.revision,null,null,null,'Ajuste de data',null);
  select * into duplicate from public.respond_public_proposal_v2(p.public_token,'alteracao',request_id,p.id,p.revision,null,null,null,'Ajuste de data',null);
  assert response.ok and duplicate.ok and response.status=duplicate.status,'Retry must return saved outcome';
  blocked:=false;
  begin perform public.respond_public_proposal_v2(p.public_token,'alteracao',request_id,p.id,p.revision,null,null,null,'Outro ajuste',null);
  exception when others then blocked:=true; end;
  assert blocked,'Idempotency key cannot accept another payload';
  blocked:=false;
  begin perform public.submit_public_quote_request(gen_random_uuid(),'[]'); exception when others then blocked:=true; end;
  assert blocked,'Capture rejects non-object payload';
  reset role;
  assert (select count(*)=1 from event_private.public_response_requests r where r.proposal_id=p.id),'Duplicate response has only one receipt';
  update public.propostas set public_token_expires_at=now()-interval '1 day' where id=p.id returning * into p;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'email','priority@example.test','role','authenticated')::text,true);
  set local role authenticated;
  assert public.refresh_my_proposal_link(p.id)<>p.public_token,'Expired owner link must rotate';
  reset role;
  update public.propostas set public_token_revoked_at=now() where id=p.id;
  set local role authenticated;
  blocked:=false;
  begin perform public.refresh_my_proposal_link(p.id); exception when others then blocked:=true; end;
  assert blocked,'Owner cannot reactivate revoked link';
  reset role;
end $$;
rollback;
